---
kind: Service
apiVersion: v1
metadata:
  namespace: apollo-example
  name: service-mysql-for-apollo-prod-env
  labels:
    app: service-mysql-for-apollo-prod-env
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  sessionAffinity: None

---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: apollo-example
  name: service-mysql-for-apollo-prod-env
subsets:
  - addresses:
      - ip: 192.168.6.170
    ports:
      - protocol: TCP
        port: 3306