
---
# configmap for apollo-admin-server-test-alpha
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: apollo-example
  name: configmap-apollo-admin-server-test-alpha
data:
  application-github.properties: |
    # 注意修改正确的namespace
    spring.datasource.url = jdbc:mysql://service-mysql-for-apollo-test-alpha-env.apollo-example:3306/TestAlphaApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = apollo
    spring.datasource.password = apollo
    eureka.service.url = http://statefulset-apollo-config-server-test-alpha-0.service-apollo-meta-server-test-alpha:8080/eureka/

---
kind: Service
apiVersion: v1
metadata:
  namespace: apollo-example
  name: service-apollo-admin-server-test-alpha
  labels:
    app: service-apollo-admin-server-test-alpha
spec:
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: pod-apollo-admin-server-test-alpha
  type: ClusterIP
  sessionAffinity: ClientIP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: apollo-example
  name: deployment-apollo-admin-server-test-alpha
  labels:
    app: deployment-apollo-admin-server-test-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-apollo-admin-server-test-alpha
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-admin-server-test-alpha
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-apollo-admin-server-test-alpha
              topologyKey: kubernetes.io/hostname
      
      volumes:
        - name: volume-configmap-apollo-admin-server-test-alpha
          configMap:
            name: configmap-apollo-admin-server-test-alpha
            items:
              - key: application-github.properties
                path: application-github.properties
      
      initContainers:
        - image: harbor.gzky.com/devops-example/apollo-alpine-bash:3.8
          name: check-service-apollo-config-server-test-alpha
          # 注意修改正确的namespace
          command: ['bash', '-c', "curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1 --retry-max-time 120 service-apollo-config-server-test-alpha.apollo-example:8080"]
      
      containers:
        - image: harbor.gzky.com/devops-example/apollo-admin-server:v1.6.0
          imagePullPolicy: Always
          #imagePullPolicy: IfNotPresent
          name: container-apollo-admin-server-test-alpha
          ports:
            - protocol: TCP
              containerPort: 8090
          
          volumeMounts:
            - name: volume-configmap-apollo-admin-server-test-alpha
              mountPath: /apollo-admin-server/config/application-github.properties
              subPath: application-github.properties
          
          env:
            - name: APOLLO_ADMIN_SERVICE_NAME
              # 注意修改正确的namespace
              value: "service-apollo-admin-server-test-alpha.apollo-example"
          
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 120
            periodSeconds: 10
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always