
---
# configmap for apollo-config-server-test-alpha
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: apollo-example
  name: configmap-apollo-config-server-test-alpha
data:
  application-github.properties: |
    # 注意修改正确的namespace
    spring.datasource.url = jdbc:mysql://service-mysql-for-apollo-test-alpha-env.apollo-example:3306/TestAlphaApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = apollo
    spring.datasource.password = apollo
    eureka.service.url = http://statefulset-apollo-config-server-test-alpha-0.service-apollo-meta-server-test-alpha:8080/eureka/

---
kind: Service
apiVersion: v1
metadata:
  namespace: apollo-example
  name: service-apollo-meta-server-test-alpha
  labels:
    app: service-apollo-meta-server-test-alpha
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-apollo-config-server-test-alpha
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: Service
apiVersion: v1
metadata:
  namespace: apollo-example
  name: service-apollo-config-server-test-alpha
  labels:
    app: service-apollo-config-server-test-alpha
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
  selector:
    app: pod-apollo-config-server-test-alpha
  type: NodePort
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: apollo-example
  name: statefulset-apollo-config-server-test-alpha
  labels:
    app: statefulset-apollo-config-server-test-alpha
spec:
  serviceName: service-apollo-meta-server-test-alpha
  replicas: 1
  selector:
    matchLabels:
      app: pod-apollo-config-server-test-alpha
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-apollo-config-server-test-alpha
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-apollo-config-server-test-alpha
              topologyKey: kubernetes.io/hostname
      
      volumes:
        - name: volume-configmap-apollo-config-server-test-alpha
          configMap:
            name: configmap-apollo-config-server-test-alpha
            items:
              - key: application-github.properties
                path: application-github.properties
      
      containers:
        - image: harbor.gzky.com/devops-example/apollo-config-server:v1.6.0
          imagePullPolicy: Always
          #imagePullPolicy: IfNotPresent
          name: container-apollo-config-server-test-alpha
          ports:
            - protocol: TCP
              containerPort: 8080
          
          volumeMounts:
            - name: volume-configmap-apollo-config-server-test-alpha
              mountPath: /apollo-config-server/config/application-github.properties
              subPath: application-github.properties
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              # 注意修改正确的namespace
              value: "service-apollo-config-server-test-alpha.apollo-example"
          
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          
      dnsPolicy: ClusterFirst
      restartPolicy: Always